export const unpluggedBooks = [
  {
    author: "Daniella Efrach",
    blurb: "Transform input to output with math operations.",
    bookCover: "/color_1.png",
    category: "UNPLUGGED",
    courses: [],
    coverImage:
      "https://codekids-minio.endeavour.cs.vt.edu/codekids/unplugged/math-operations.png",
    id: 9999999,
    owner: null,
    ownerId: 16,
    pages: [],
    published: true,
    readyForPublish: false,
    tags: [],
    title: "Math Input/Output Activity",
    link: "math_io_pipeline_functions.pdf",
  },
  {
    author: "Thomas",
    blurb: "Learn about loops and abstraction through a maze.",
    bookCover: "/color_7.png",
    category: "UNPLUGGED",
    courses: [],
    coverImage:
      "https://codekids-minio.endeavour.cs.vt.edu/codekids/unplugged/arrow.png",
    id: 9999998,
    owner: null,
    ownerId: 16,
    pages: [],
    published: true,
    readyForPublish: false,
    tags: [],
    title: "Maze Solver Game",
    link: "maze_solver.pdf",
  },
  {
    author: "Thomas",
    blurb: "A matching game with computer components.",
    bookCover: "/color_4.png",
    category: "UNPLUGGED",
    courses: [],
    coverImage:
      "https://codekids-minio.endeavour.cs.vt.edu/codekids/unplugged/deck-of-cards-clipart-sm.png",
    id: 9999997,
    owner: null,
    ownerId: 16,
    pages: [],
    published: true,
    readyForPublish: false,
    tags: [],
    title: "Card Game",
    link: "CardGames.pdf",
  },
  {
    author: "Zoe Hite",
    blurb: "Grid puzzle activity teaching algorithms.",
    bookCover: "/color_2.png",
    category: "UNPLUGGED",
    courses: [],
    coverImage:
      "https://codekids-minio.endeavour.cs.vt.edu/codekids/unplugged/mazeIcon.png",
    id: 9999996,
    owner: null,
    ownerId: 16,
    pages: [],
    published: true,
    readyForPublish: false,
    tags: [],
    title: "Grid Puzzle",
    link: "GridPuzzleAlgorithms.pdf",
  },
  {
    author: "Vee",
    blurb: "Learn about reinforcement learning using Skittles!",
    bookCover: "/color_3.png",
    category: "UNPLUGGED",
    courses: [],
    coverImage:
      "https://codekids-minio.endeavour.cs.vt.edu/codekids/unplugged/rl_skittles.png",
    id: 9999995,
    owner: null,
    ownerId: 16,
    pages: [],
    published: true,
    readyForPublish: false,
    tags: [],
    title: "Reinforcement Learning with Skittles",
    link: "Reinforcement_Learning_With_Skittles.pdf",
  },
  {
    author: "Norah",
    blurb: "Learn about computer parallelization!",
    bookCover: "/color_5.png",
    category: "UNPLUGGED",
    courses: [],
    coverImage:
      "https://codekids-minio.endeavour.cs.vt.edu/codekids/unplugged/Parallelization_Icon.png",
    id: 9999994,
    owner: null,
    ownerId: 16,
    pages: [],
    published: true,
    readyForPublish: false,
    tags: [],
    title: "Parallelization",
    link: "Parallelization_Activity.pdf",
  },
];
