export const unpluggedBooks = [
  {
    author: "Daniella Efrach",
    blurb: "Transform input to output with math operations",
    bookCover: "/color_1.png",
    category: "UNPLUGGED",
    courses: [],
    coverImage:
      "https://codekids-minio.endeavour.cs.vt.edu/codekids/unplugged/math-operations.png",
    id: 9999999,
    owner: null,
    ownerId: 16,
    pages: [],
    published: true,
    readyForPublish: false,
    tags: [],
    title: "Math Input/Output Activity",
    link: "math_io_pipeline_functions.pdf",
  },
  {
    author: "Thomas",
    blurb: "Learn about loops and abstraction through a maze",
    bookCover: "/color_7.png",
    category: "UNPLUGGED",
    courses: [],
    coverImage:
      "https://codekids-minio.endeavour.cs.vt.edu/codekids/unplugged/arrow.png",
    id: 9999998,
    owner: null,
    ownerId: 16,
    pages: [],
    published: true,
    readyForPublish: false,
    tags: [],
    title: "Maze Solver Game",
    link: "Maze_Solver.pdf",
  },
  {
    author: "Thomas",
    blurb: "A matching game with computer components",
    bookCover: "/color_4.png",
    category: "UNPLUGGED",
    courses: [],
    coverImage:
      "https://codekids-minio.endeavour.cs.vt.edu/codekids/unplugged/deck-of-cards-clipart-sm.png",
    id: 9999997,
    owner: null,
    ownerId: 16,
    pages: [],
    published: true,
    readyForPublish: false,
    tags: [],
    title: "Card Game",
    link: "CardGames.pdf",
  },
];
